CREATE DATABASE simple_crm;
USE simple_crm;

CREATE TABLE IF NOT EXISTS user (
    id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    password CHAR(32) NOT NULL,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    disabled BOOLEAN,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS role (
    id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
) ENGINE=INNODB;

INSERT INTO role (name) values ('admin');
INSERT INTO role (name) values ('publisher');

CREATE TABLE IF NOT EXISTS user_role (
    id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id SMALLINT UNSIGNED NOT NULL,
    role_id SMALLINT UNSIGNED NOT NULL,
    CONSTRAINT uk_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_user
    FOREIGN KEY (user_id) REFERENCES user (id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
    CONSTRAINT fk_role
    FOREIGN KEY (role_id) REFERENCES role (id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
)  ENGINE=INNODB;